use_frameworks!

platform :ios, '8.0'

target 'TIRouterAction_Example' do
  pod 'TIRouterAction', :path => '../'

  target 'TIRouterAction_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
