use_frameworks!

platform :ios, '8.0'

target 'NLNetwork_Example' do
  pod 'NLNetwork', :path => '../'

  target 'NLNetwork_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
