use_frameworks!

platform :ios, '8.0'

target 'NLModelService_Example' do
  pod 'NLModelService', :path => '../'

  target 'NLModelService_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
