platform :osx, '10.10'

if File::exist?("Podfile.lock")
  `rm Podfile.lock`
end

use_frameworks!

target 'TopicExtractor_Example' do
  supports_swift_versions '<= 4.2'
  pod 'TopicExtractor', :path => '../'
  pod 'Alamofire', '~> 4.9'
  pod 'MCFrontendKit', :path => '../../../../MCFrontendService'

  target 'TopicExtractor_Tests' do
    inherit! :search_paths

    
  end
end
