use_frameworks!

platform :ios, '8.0'

target 'NLFoundation_Example' do
  pod 'NLFoundation', :path => '../'

  target 'NLFoundation_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
