use_frameworks!

platform :ios, '9.0'

target 'PureObjCLib_Example' do
  pod 'PureObjCLib', :path => '../'

  target 'PureObjCLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
