use_frameworks!

platform :ios, '8.0'

target 'NLExtension_Example' do
  pod 'NLExtension', :path => '../'

  target 'NLExtension_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
