# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

if Gem::Version.new(`pod --version`) >= Gem::Version.new('1.7.5')
    install! 'cocoapods',
    :generate_multiple_pod_projects => true,
    :incremental_installation => true
    else
    raise 'cocoapods 最低要求1.7.5'
    return
end

if File.exists?("Podfile.lock")
  `rm Podfile.lock`
end

target 'FoundationDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FoundationDemo
  # pod 'Peregrine', :path => '../../../Peregrine'
  pod 'TIRouterAction', :path => '../TIRouterAction'
  pod 'MBProgressHUD'
  pod 'MCUIKit'
  pod 'MCJSONKit'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'Weibo_SDK', '~> 3.2'
  pod 'Realm', '~> 3.2'
  pod 'SDWebImage'
  pod 'MJRefresh'

  target 'FoundationDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Specta'
    pod 'Expecta'
  end

end

post_install do |installer|
    require_relative 'Pods/Peregrine/Peregrine/PGConfiguration.rb'
    PGConfiguration::configure_project(installer)
end
