# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FoundationDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FoundationDemo
  pod 'Peregrine', '~> 0.2.0'
  pod 'MCLogger', :path => '../../../MCLogger'
  pod 'MBProgressHUD'
  pod 'MCUIKit'
  pod 'Masonry'
  pod 'AFNetworking'

  target 'FoundationDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Specta'
    pod 'Expecta'
  end

end
