# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

`rm Podfile.lock`

target 'FoundationDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FoundationDemo
  pod 'Peregrine', '~> 0.4'
  pod 'MCLogger', :path => '../../../MCLogger'
  pod 'TIRouterAction', :path => '../TIRouterAction'
  pod 'MBProgressHUD'
  pod 'MCUIKit'
  pod 'Masonry'
  pod 'AFNetworking'

  target 'FoundationDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Specta'
    pod 'Expecta'
  end

end

post_install do |installer|
#     require File.expand_path('PGConfiguration.rb', installer.sandbox.root.to_s + '/Peregrine/Peregrine/')
#     PGConfiguration::configure_project(installer)
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO"
#    end
#  end
end
