use_frameworks!

platform :ios, '8.0'

target 'NLUtility_Example' do
  pod 'NLUtility', :path => '../'

  target 'NLUtility_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
