use_frameworks!

platform :ios, '8.0'

target 'NLUIComponent_Example' do
  pod 'NLUIComponent', :path => '../'

  target 'NLUIComponent_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
