use_frameworks!

platform :ios, '8.0'

target 'NLWeibo_Example' do
  pod 'NLWeibo', :path => '../'

  target 'NLWeibo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
