use_frameworks!

platform :ios, '9.0'

target 'MixedLib_Example' do
  pod 'MixedLib', :path => '../'

  target 'MixedLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
