use_frameworks!

platform :ios, '9.0'

target 'HybridLib_Example' do
  pod 'HybridLib', :path => '../'

  target 'HybridLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
