use_frameworks!

platform :ios, '8.0'

target 'NLModuleService_Example' do
  pod 'NLModuleService', :path => '../'

  target 'NLModuleService_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
