# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

`rm Podfile.lock`

target 'UIKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSGuide
  # pod 'Peregrine', :path => '../Peregrine'
  # pod 'Peregrine', :git => 'git@github.com:BinaryParadise/Peregrine.git', :branch => 'master'
  pod 'Peregrine', '~> 0.3.0'
  pod 'MCLogger', '~> 0.1'
  pod 'TIRouterAction', :path => '../TIRouterAction'

end

post_install do |installer|
  # require File.expand_path('PGConfiguration.rb', installer.sandbox.root.to_s + '/Peregrine/Peregrine/')
  # PGConfiguration::configure_project(installer)
end
