# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'UIKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSGuide
  # pod 'Peregrine', :path => '../Peregrine'
  # pod 'Peregrine', :git => 'git@github.com:BinaryParadise/Peregrine.git', :branch => 'master'
  pod 'Peregrine', '~> 0.2.3'
  pod 'MCLogger'

end

post_install do |installer|

  # require File.expand_path('ProjectConfigurator.rb', installer.sandbox.root.to_s + '/..')
  # ProjectConfigurator::configure_project(installer)

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          # config.build_settings['CC'] = '${CCROOT}/bin/clang'
          # config.build_settings['CCROOT'] = '/usr/local'
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = 'NO'
          # cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
          # cflags << '$(inherited) -Xclang -load -Xclang ${CCROOT}/lib/PeregrinePlugin.dylib -Xclang -add-plugin -Xclang PeregrinePlugin -Xclang -plugin-arg-PeregrinePlugin -Xclang ${PODS_ROOT}'
        end
    end
end
