# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

if Gem::Version.new(`pod --version`) >= Gem::Version.new('1.7.5')
    install! 'cocoapods',
    :generate_multiple_pod_projects => true,
    :incremental_installation => true
    else
    raise 'cocoapods 最低要求1.7.5'
    return
end

if File.exists?("Podfile.lock")
  `rm Podfile.lock`
end

target 'Neverland' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Neverland
  pod 'MBProgressHUD'
  pod 'NLRouterAction', :path => '../NLRouterAction'
  pod 'MCJSONKit', :path => '../../../MCJSONKit'
  pod 'NLModuleService', :path => '../NLModuleService'
  pod 'NLModelService', :path => '../NLModelService'
  pod 'NLFoundation', :path => '../NLFoundation'
  pod 'NLDataType', :path => '../NLDataType'
  pod 'NLWeibo', :path => '../NLWeibo'
  pod 'NLLogger', :path => '../NLLogger'
  pod 'NLUtility', :path => '../NLUtility'
  pod 'NLUIComponent', :path => '../NLUIComponent'
  pod 'NLProtocols', :path => '../NLProtocols'
  pod 'NLExtension', :path => '../NLExtension'
  pod 'Masonry'
  pod 'MCObserverKit'
  pod 'MLeaksFinder'
#  pod 'Peregrine', :path => '../../../Peregrine'
end

post_install do |installer|
    require_relative '../../../Peregrine/Peregrine/PGConfiguration.rb'
    PGConfiguration::configure_project(installer)

    `efpodsanalyzer ../Neverland/Podfile`
end
